platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!

target 'appstarter-pod-ios_Example' do
  pod 'appstarter-pod-ios', :path => '../'

  target 'appstarter-pod-ios_Tests' do
    inherit! :search_paths

    
  end
end
