//
//  DependencyManager.swift
//  appstarter-pod-ios
//
//  Created by Gabrielle Earnshaw on 08/07/2019.
//

import Foundation

/// The class that handles dependency management
public class DependencyManager {
    // TODO: Implement - Add autogenerated version of the dependency manager
    public var testDependency = 10
}
